version: '3.8'
services:
  frontend:
    build: .
    container_name: frontend-service
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]
    restart: unless-stopped
